//! AI tool hook integrations (goals 321-324).
//!
//! Provides hook scripts and configuration generators for AI coding tools
//! so that PledgeGuard scans prompts, file reads, and commands *before*
//! AI execution — preventing secrets from being sent to LLM APIs.
//!
//! ## Supported tools
//!
//! | Tool | Hook mechanism | What gets scanned |
//! |---|---|---|
//! | Cursor | `.cursor/hooks` pre-prompt hook | Prompt text + file contents |
//! | Claude Code | `.claude/hooks` pre-tool hook | Commands + file contents |
//! | GitHub Copilot | `.github/copilot-hooks` pre-suggestion hook | Inline suggestions context |
//! | OpenAI Codex | `.codex/hooks` pre-execution hook | Commands + file diffs |
//!
//! All hooks call `pledgeguard scan -` (stdin mode) with `--fail-on-findings`
//! so any detected secret blocks the AI action and prints a warning.

use std::fmt::Write;

/// Shell script header common to all hooks.
const HOOK_HEADER: &str = "#!/bin/sh\n# PledgeGuard AI hook — scans for secrets before AI execution.\n# Generated by `pledgeguard install-ai-hooks`.\n";

/// Returns the Cursor pre-prompt hook script.
///
/// Cursor invokes this hook before sending a prompt to the model.
/// The hook receives the prompt text on stdin; if any secret is found,
/// it exits non-zero to block the prompt.
pub fn cursor_hook() -> String {
    let mut s = String::from(HOOK_HEADER);
    s.push_str("# Cursor pre-prompt hook: scan prompt + attached file contents for secrets.\n");
    s.push_str("# If secrets are found, the prompt is blocked.\n");
    s.push_str("pledgeguard scan - --fail-on-findings --format json 2>/dev/null\n");
    s.push_str("exit $?\n");
    s
}

/// Returns the `.cursor/hooks.json` configuration snippet that registers
/// the pre-prompt hook.
pub fn cursor_config() -> String {
    r#"{
  "hooks": {
    "prePrompt": [
      {
        "command": ".cursor/hooks/pledgeguard-pre-prompt.sh",
        "timeout": 10000
      }
    ]
  }
}
"#
    .to_string()
}

/// Returns the Claude Code pre-tool hook script.
///
/// Claude Code invokes this hook before executing a tool (file read,
/// bash command, etc.). The hook receives the tool input on stdin.
pub fn claude_code_hook() -> String {
    let mut s = String::from(HOOK_HEADER);
    s.push_str(
        "# Claude Code pre-tool hook: scan tool inputs (commands, file contents) for secrets.\n",
    );
    s.push_str("# If secrets are found, the tool execution is blocked.\n");
    s.push_str("pledgeguard scan - --fail-on-findings --format json 2>/dev/null\n");
    s.push_str("exit $?\n");
    s
}

/// Returns the `.claude/hooks.json` configuration snippet.
pub fn claude_code_config() -> String {
    r#"{
  "hooks": {
    "preTool": [
      {
        "command": ".claude/hooks/pledgeguard-pre-tool.sh",
        "timeout": 10000
      }
    ]
  }
}
"#
    .to_string()
}

/// Returns the GitHub Copilot pre-suggestion hook script.
///
/// Copilot invokes this hook before generating an inline suggestion.
/// The hook receives the surrounding code context on stdin.
pub fn copilot_hook() -> String {
    let mut s = String::from(HOOK_HEADER);
    s.push_str("# GitHub Copilot pre-suggestion hook: scan surrounding context for secrets.\n");
    s.push_str("# If secrets are found, the suggestion is blocked.\n");
    s.push_str("pledgeguard scan - --fail-on-findings --format json 2>/dev/null\n");
    s.push_str("exit $?\n");
    s
}

/// Returns the `.github/copilot-hooks.json` configuration snippet.
pub fn copilot_config() -> String {
    r#"{
  "hooks": {
    "preSuggestion": [
      {
        "command": ".github/hooks/pledgeguard-pre-suggestion.sh",
        "timeout": 10000
      }
    ]
  }
}
"#
    .to_string()
}

/// Returns the OpenAI Codex pre-execution hook script.
///
/// Codex invokes this hook before executing a generated command or
/// applying a file diff. The hook receives the command/diff on stdin.
pub fn codex_hook() -> String {
    let mut s = String::from(HOOK_HEADER);
    s.push_str("# OpenAI Codex pre-execution hook: scan commands + file diffs for secrets.\n");
    s.push_str("# If secrets are found, execution is blocked.\n");
    s.push_str("pledgeguard scan - --fail-on-findings --format json 2>/dev/null\n");
    s.push_str("exit $?\n");
    s
}

/// Returns the `.codex/hooks.json` configuration snippet.
pub fn codex_config() -> String {
    r#"{
  "hooks": {
    "preExecution": [
      {
        "command": ".codex/hooks/pledgeguard-pre-execution.sh",
        "timeout": 10000
      }
    ]
  }
}
"#
    .to_string()
}

/// All supported AI tools.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AiTool {
    Cursor,
    ClaudeCode,
    Copilot,
    Codex,
}

impl AiTool {
    /// Returns the human-readable name.
    pub fn name(&self) -> &'static str {
        match self {
            AiTool::Cursor => "Cursor",
            AiTool::ClaudeCode => "Claude Code",
            AiTool::Copilot => "GitHub Copilot",
            AiTool::Codex => "OpenAI Codex",
        }
    }

    /// Returns the hook script content.
    pub fn hook_script(&self) -> String {
        match self {
            AiTool::Cursor => cursor_hook(),
            AiTool::ClaudeCode => claude_code_hook(),
            AiTool::Copilot => copilot_hook(),
            AiTool::Codex => codex_hook(),
        }
    }

    /// Returns the config file content.
    pub fn config_content(&self) -> String {
        match self {
            AiTool::Cursor => cursor_config(),
            AiTool::ClaudeCode => claude_code_config(),
            AiTool::Copilot => copilot_config(),
            AiTool::Codex => codex_config(),
        }
    }

    /// Returns the directory where the hook script should be installed
    /// (relative to the project root).
    pub fn hook_dir(&self) -> &'static str {
        match self {
            AiTool::Cursor => ".cursor/hooks",
            AiTool::ClaudeCode => ".claude/hooks",
            AiTool::Copilot => ".github/hooks",
            AiTool::Codex => ".codex/hooks",
        }
    }

    /// Returns the config file path (relative to the project root).
    pub fn config_path(&self) -> &'static str {
        match self {
            AiTool::Cursor => ".cursor/hooks.json",
            AiTool::ClaudeCode => ".claude/hooks.json",
            AiTool::Copilot => ".github/copilot-hooks.json",
            AiTool::Codex => ".codex/hooks.json",
        }
    }

    /// Returns the hook script filename.
    pub fn hook_filename(&self) -> &'static str {
        match self {
            AiTool::Cursor => "pledgeguard-pre-prompt.sh",
            AiTool::ClaudeCode => "pledgeguard-pre-tool.sh",
            AiTool::Copilot => "pledgeguard-pre-suggestion.sh",
            AiTool::Codex => "pledgeguard-pre-execution.sh",
        }
    }

    /// Returns all supported tools.
    pub fn all() -> &'static [AiTool] {
        &[
            AiTool::Cursor,
            AiTool::ClaudeCode,
            AiTool::Copilot,
            AiTool::Codex,
        ]
    }
}

/// Result of installing hooks for a single tool.
#[derive(Debug)]
pub struct HookInstallResult {
    pub tool: AiTool,
    pub hook_path: String,
    pub config_path: String,
    pub success: bool,
    pub error: Option<String>,
}

/// Installs hook scripts and config files for the specified AI tools
/// into the given project root directory. Creates directories as needed.
/// Returns a result for each tool.
pub fn install_hooks(root: &std::path::Path, tools: &[AiTool]) -> Vec<HookInstallResult> {
    tools
        .iter()
        .map(|&tool| install_one_hook(root, tool))
        .collect()
}

fn install_one_hook(root: &std::path::Path, tool: AiTool) -> HookInstallResult {
    let hook_dir = root.join(tool.hook_dir());
    let hook_path = hook_dir.join(tool.hook_filename());
    let config_path = root.join(tool.config_path());

    let result = (|| -> Result<(), String> {
        std::fs::create_dir_all(&hook_dir)
            .map_err(|e| format!("failed to create {}: {e}", hook_dir.display()))?;

        std::fs::write(&hook_path, tool.hook_script())
            .map_err(|e| format!("failed to write {}: {e}", hook_path.display()))?;

        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            if let Ok(meta) = std::fs::metadata(&hook_path) {
                let mut perms = meta.permissions();
                perms.set_mode(0o755);
                let _ = std::fs::set_permissions(&hook_path, perms);
            }
        }

        std::fs::write(&config_path, tool.config_content())
            .map_err(|e| format!("failed to write {}: {e}", config_path.display()))?;

        Ok(())
    })();

    HookInstallResult {
        tool,
        hook_path: hook_path.display().to_string(),
        config_path: config_path.display().to_string(),
        success: result.is_ok(),
        error: result.err(),
    }
}

/// Generates a summary of all installed hooks for display.
pub fn format_install_summary(results: &[HookInstallResult]) -> String {
    let mut out = String::new();
    for r in results {
        if r.success {
            let _ = writeln!(
                out,
                "  {} → {} + {}",
                r.tool.name(),
                r.hook_path,
                r.config_path
            );
        } else if let Some(ref err) = r.error {
            let _ = writeln!(out, "  {} → FAILED: {err}", r.tool.name());
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_all_tools_have_scripts() {
        for &tool in AiTool::all() {
            let script = tool.hook_script();
            assert!(script.contains("pledgeguard scan"));
            assert!(script.contains("--fail-on-findings"));

            let config = tool.config_content();
            assert!(config.contains("hooks"));
        }
    }

    #[test]
    fn test_hook_dirs_are_distinct() {
        let dirs: Vec<_> = AiTool::all().iter().map(|t| t.hook_dir()).collect();
        let unique: std::collections::HashSet<_> = dirs.iter().collect();
        assert_eq!(dirs.len(), unique.len());
    }

    #[test]
    fn test_install_hooks_creates_files() {
        let tmp = tempfile::tempdir().unwrap();
        let results = install_hooks(tmp.path(), AiTool::all());
        assert_eq!(results.len(), 4);
        for r in &results {
            assert!(r.success, "{} failed: {:?}", r.tool.name(), r.error);
            assert!(std::path::Path::new(&r.hook_path).exists());
            assert!(std::path::Path::new(&r.config_path).exists());
        }
    }
}
