//! False-positive reduction filters for goals 264-280.
//!
//! This module provides path-based, content-based, and pattern-based
//! filters that suppress findings likely to be false positives without
//! dropping real secrets.

use crate::finding::Finding;
use std::path::Path;

// ── 264: .env file-aware scanning ───────────────────────────────────────

/// Parse .env file content and return lines that are not commented out.
/// Returns (line_number, line_content) pairs for active KEY=VALUE lines.
pub fn parse_env_active_lines(content: &str) -> Vec<(usize, String)> {
    let mut result = Vec::new();
    for (i, line) in content.lines().enumerate() {
        let trimmed = line.trim();
        if trimmed.is_empty() || trimmed.starts_with('#') {
            continue;
        }
        if !trimmed.contains('=') {
            continue;
        }
        result.push((i + 1, line.to_string()));
    }
    result
}

/// Returns true if the file path looks like a .env file.
pub fn is_env_file(path: &Path) -> bool {
    let name = path.file_name().and_then(|n| n.to_str()).unwrap_or("");
    name == ".env"
        || name.starts_with(".env.")
        || name.ends_with(".env")
        || name == ".envrc"
}

// ── 266: Documentation path detection ───────────────────────────────────

const DOC_MARKERS: &[&str] = &[
    "docs",
    "doc",
    "documentation",
    "README",
    "readme",
    "CHANGELOG",
    "changelog",
    "CONTRIBUTING",
    "contributing",
    "LICENSE",
    "license",
    "AUTHORS",
    "authors",
    "wiki",
    "help",
];

/// Returns true if the path appears to be in a documentation directory
/// or is a documentation file.
pub fn is_documentation_path(path: &Path) -> bool {
    let path_str = path.to_string_lossy();
    for marker in DOC_MARKERS {
        if path_str.contains(marker) {
            return true;
        }
    }
    if let Some(name) = path.file_name().and_then(|n| n.to_str()) {
        let lower = name.to_lowercase();
        if lower.ends_with(".md")
            || lower.ends_with(".rst")
            || lower.ends_with(".txt")
            || lower == "readme"
            || lower == "changelog"
            || lower == "license"
        {
            return true;
        }
    }
    false
}

// ── 267: Generated file detection ───────────────────────────────────────

const GENERATED_MARKERS: &[&str] = &[
    "DO NOT EDIT",
    "do not edit",
    "auto-generated",
    "autogenerated",
    "generated by",
    "code generated",
    "Code generated",
    "AUTO-GENERATED",
    "@generated",
    "This file was automatically generated",
    "This code was generated",
    "DO NOT MODIFY",
    "do not modify",
];

/// Returns true if the file content contains a generated-file marker
/// within the first few lines.
pub fn is_generated_content(content: &str) -> bool {
    for line in content.lines().take(20) {
        for marker in GENERATED_MARKERS {
            if line.contains(marker) {
                return true;
            }
        }
    }
    false
}

/// Returns true if the file path suggests it's a generated file.
pub fn is_generated_path(path: &Path) -> bool {
    let path_str = path.to_string_lossy();
    let checks = [
        "/generated/", "\\generated\\", "generated/", "generated\\",
        "/.gen/", "/dist/", "\\dist\\", "dist/", "dist\\",
        "/build/", "\\build\\", "build/", "build\\",
        "/target/", "\\target\\", "target/", "target\\",
        "/.next/", "/out/", "\\out\\", "out/", "out\\",
    ];
    for c in checks {
        if path_str.contains(c) || path_str.starts_with(c) {
            return true;
        }
    }
    path_str.ends_with(".generated.go")
        || path_str.ends_with(".gen.go")
        || path_str.ends_with("_generated.go")
        || path_str.ends_with(".pb.go")
        || path_str.ends_with(".pb.dart")
        || path_str.ends_with(".g.dart")
}

// ── 268: Vendored dependency detection ──────────────────────────────────

const VENDOR_DIRS: &[&str] = &[
    "vendor",
    "node_modules",
    "third_party",
    "thirdparty",
    "deps",
    ".deps",
    "bower_components",
    "jspm_packages",
    "packages",
    ".cargo",
    "go.sum",
    "go.mod",
];

/// Returns true if the path is inside a vendored dependency directory.
pub fn is_vendored_path(path: &Path) -> bool {
    let path_str = path.to_string_lossy();
    for dir in VENDOR_DIRS {
        let unix = format!("/{dir}/");
        let windows = format!("\\{dir}\\");
        let starts_unix = format!("{dir}/");
        let starts_windows = format!("{dir}\\");
        if path_str.contains(&unix)
            || path_str.contains(&windows)
            || path_str.starts_with(&starts_unix)
            || path_str.starts_with(&starts_windows)
        {
            return true;
        }
    }
    false
}

// ── 269: Minified file detection ────────────────────────────────────────

/// Returns true if the file path suggests a minified file.
pub fn is_minified_path(path: &Path) -> bool {
    let name = path.file_name().and_then(|n| n.to_str()).unwrap_or("");
    name.contains(".min.")
        || name.contains("-min.")
        || name.contains(".production.")
        || name.contains(".prod.")
}

// ── 270: Lock file detection ────────────────────────────────────────────

const LOCK_FILES: &[&str] = &[
    "package-lock.json",
    "yarn.lock",
    "pnpm-lock.yaml",
    "Cargo.lock",
    "Gemfile.lock",
    "composer.lock",
    "poetry.lock",
    "Pipfile.lock",
    "go.sum",
    "flake.lock",
    "gradle.lockfile",
    "packages.lock.json",
    "vcpkg.lock",
];

/// Returns true if the file is a known lock file.
pub fn is_lock_file(path: &Path) -> bool {
    let name = path.file_name().and_then(|n| n.to_str()).unwrap_or("");
    LOCK_FILES.contains(&name)
}

// ── 271: Binary file detection ──────────────────────────────────────────

/// Returns true if the content appears to be binary (contains null bytes
/// or a high proportion of non-text bytes).
pub fn is_binary_content(content: &[u8]) -> bool {
    if content.is_empty() {
        return false;
    }
    // Check for null bytes — strong binary indicator.
    if content.contains(&0u8) {
        return true;
    }
    // Check for UTF-8 validity.
    if std::str::from_utf8(content).is_err() {
        return true;
    }
    // Check proportion of non-printable characters.
    let sample_len = content.len().min(1024);
    let non_printable = content[..sample_len]
        .iter()
        .filter(|&&b| b < 0x20 && b != b'\n' && b != b'\r' && b != b'\t')
        .count();
    let ratio = non_printable as f64 / sample_len as f64;
    ratio > 0.30
}

// ── 272: Certificate file detection ─────────────────────────────────────

const CERT_EXTENSIONS: &[&str] = &["pem", "crt", "key", "cer", "der", "pfx", "p12", "jks"];

const CA_PATH_MARKERS: &[&str] = &["/etc/ssl/", "/etc/pki/", "/usr/local/share/ca-certificates/", "/usr/share/ca-certificates/", "ca-bundle", "ca-certificates"];

/// Returns true if the file is a certificate file in a known CA path.
pub fn is_ca_certificate_path(path: &Path) -> bool {
    let ext = path
        .extension()
        .and_then(|e| e.to_str())
        .map(|s| s.to_lowercase());
    if !ext.map(|e| CERT_EXTENSIONS.contains(&e.as_str())).unwrap_or(false) {
        return false;
    }
    let path_str = path.to_string_lossy();
    CA_PATH_MARKERS.iter().any(|m| path_str.contains(m))
}

// ── 273: Example value detection ────────────────────────────────────────

const EXAMPLE_MARKERS: &[&str] = &[
    "EXAMPLE",
    "example",
    "PLACEHOLDER",
    "placeholder",
    "CHANGEME",
    "changeme",
    "CHANGEME!",
    "TODO",
    "todo",
    "FIXME",
    "fixme",
    "YOUR_",
    "your_",
    "YOUR-",
    "your-",
    "REPLACE",
    "replace",
    "DUMMY",
    "dummy",
    "FAKE",
    "fake",
    "TEST",
    "test",
    "SAMPLE",
    "sample",
    "DEMO",
    "demo",
    "XXXX",
    "xxxx",
];

/// Returns true if the matched text contains an example/placeholder marker.
pub fn is_example_value(matched: &str) -> bool {
    EXAMPLE_MARKERS.iter().any(|m| matched.contains(m))
}

// ── 274: Canary token detection ─────────────────────────────────────────

const CANARY_TOKENS: &[&str] = &[
    "AKIAIOSFODNN7EXAMPLE",
    "AKIAEXAMPLE",
    "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY",
    "ghp_example",
    "gho_example",
    "ghs_example",
    "ghr_example",
    "github_pat_example",
    "xoxb-example",
    "xoxp-example",
    "sk-test",
    "sk-example",
    "test-token",
    "example-token",
    "1234567890",
    "aaaaaaaaaaaa",
    "000000000000",
];

/// Returns true if the matched text is a known canary/fake token.
pub fn is_canary_token(matched: &str) -> bool {
    let matched_upper = matched.to_uppercase();
    CANARY_TOKENS.iter().any(|t| {
        matched == *t || matched_upper == t.to_uppercase() || matched.contains(t)
    })
}

// ── 275: Context-aware entropy ──────────────────────────────────────────

/// Returns an adjusted entropy threshold based on file type/context.
/// Some file types naturally have higher entropy (e.g., minified JS)
/// and need a higher threshold to avoid false positives.
pub fn context_aware_entropy_threshold(path: &Path) -> f64 {
    let ext = path
        .extension()
        .and_then(|e| e.to_str())
        .map(|s| s.to_lowercase());

    match ext.as_deref() {
        // Minified files have high baseline entropy.
        Some("min.js") | Some("min.css") => 4.5,
        // Binary-like formats.
        Some("bin") | Some("dat") | Some("so") | Some("dll") | Some("exe") => 5.0,
        // Config files with structured data.
        Some("json") | Some("yaml") | Some("yml") | Some("toml") => 3.0,
        // .env files — keys are usually real.
        Some("env") => 2.5,
        // Source code — moderate threshold.
        Some("rs") | Some("go") | Some("py") | Some("js") | Some("ts") | Some("java") | Some("c") | Some("cpp") => 3.5,
        // Default.
        _ => {
            if is_lock_file(path) || is_minified_path(path) {
                4.5
            } else if is_env_file(path) {
                2.5
            } else {
                3.0
            }
        }
    }
}

// ── 276: Secret rotation detection ──────────────────────────────────────

/// Detects if a secret is being rotated by checking if old and new
/// values appear in the same diff. Returns the indices of findings
/// that appear to be part of a rotation (the old value being replaced).
pub fn detect_rotation(findings: &[Finding]) -> Vec<usize> {
    let mut rotated = Vec::new();
    for (i, f) in findings.iter().enumerate() {
        // Look for findings on adjacent lines with the same rule_id.
        for (j, other) in findings.iter().enumerate() {
            if i == j || f.rule_id != other.rule_id {
                continue;
            }
            // Same rule on adjacent lines in a diff context.
            let line_diff = f.line.abs_diff(other.line);
            if line_diff <= 3 && f.matched != other.matched {
                // The one with a lower line number is likely the old value.
                if f.line < other.line {
                    rotated.push(i);
                    break;
                }
            }
        }
    }
    rotated
}

// ── 277: Multi-line secret detection ────────────────────────────────────

/// Detects secrets that are split across multiple lines using
/// line continuation characters (\ at end of line in shell/config,
/// or string concatenation patterns).
pub fn join_multiline_secrets(content: &str) -> Vec<(usize, usize, String)> {
    let mut results = Vec::new();
    let lines: Vec<&str> = content.lines().collect();

    let mut i = 0;
    while i < lines.len() {
        let line = lines[i];
        // Check for line continuation.
        if line.ends_with('\\') && i + 1 < lines.len() {
            let start = i + 1;
            let mut joined = line.trim_end_matches('\\').to_string();
            let mut end = start;
            while end < lines.len() {
                let next = lines[end];
                if next.ends_with('\\') {
                    joined.push_str(next.trim_end_matches('\\'));
                    end += 1;
                } else {
                    joined.push_str(next);
                    end += 1;
                    break;
                }
            }
            if joined.len() > 20 {
                results.push((start, end, joined));
            }
            i = end;
        } else {
            i += 1;
        }
    }
    results
}

// ── 278: Hex blob filtering ─────────────────────────────────────────────

/// Returns true if the matched text looks like a hex blob (hash, commit SHA)
/// rather than a secret. Heuristics:
/// - Pure hex string of length 40 (git SHA) or 64 (SHA-256 hash)
/// - Contains only hex chars and is very long (>64 chars)
pub fn is_hex_blob(matched: &str) -> bool {
    let trimmed = matched.trim();
    if trimmed.is_empty() {
        return false;
    }
    // Check if it's all hex.
    if !trimmed.chars().all(|c| c.is_ascii_hexdigit()) {
        return false;
    }
    let len = trimmed.len();
    // Git commit SHA (40), SHA-1 hash (40), SHA-256 hash (64).
    if len == 40 || len == 64 {
        return true;
    }
    // Very long hex strings are likely blobs.
    if len > 64 {
        return true;
    }
    false
}

// ── 279: UUID filtering ─────────────────────────────────────────────────

/// Returns true if the matched text is a UUID (not an API key).
/// UUIDs have the format: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
pub fn is_uuid(matched: &str) -> bool {
    let trimmed = matched.trim();
    if trimmed.len() != 36 {
        return false;
    }
    // Check UUID format: 8-4-4-4-12 hex digits with hyphens.
    let parts: Vec<&str> = trimmed.split('-').collect();
    if parts.len() != 5 {
        return false;
    }
    let lengths = [8, 4, 4, 4, 12];
    for (part, expected_len) in parts.iter().zip(lengths.iter()) {
        if part.len() != *expected_len {
            return false;
        }
        if !part.chars().all(|c| c.is_ascii_hexdigit()) {
            return false;
        }
    }
    true
}

// ── 280: JWT structure validation ───────────────────────────────────────

/// Validates JWT structure: must have exactly 3 base64url-encoded parts
/// separated by dots, and the header must decode to valid JSON with
/// a "typ" or "alg" field.
pub fn is_valid_jwt_structure(matched: &str) -> bool {
    let trimmed = matched.trim();
    let parts: Vec<&str> = trimmed.split('.').collect();
    if parts.len() != 3 {
        return false;
    }
    // All parts must be non-empty.
    if parts.iter().any(|p| p.is_empty()) {
        return false;
    }
    // All parts must be valid base64url.
    for part in &parts {
        if !is_base64url(part) {
            return false;
        }
    }
    // Try to decode the header and check for JWT fields.
    if let Ok(header_bytes) = base64url_decode(parts[0])
        && let Ok(header_json) = std::str::from_utf8(&header_bytes)
    {
        // Check for typical JWT header fields.
        return header_json.contains("alg")
            || header_json.contains("typ")
            || header_json.contains("kid");
    }
    // Even if header decode fails, the 3-part structure is valid enough.
    parts.iter().all(|p| p.len() >= 10)
}

/// Check if a string is valid base64url encoding.
fn is_base64url(s: &str) -> bool {
    s.chars().all(|c| {
        c.is_ascii_alphanumeric() || c == '-' || c == '_' || c == '='
    })
}

/// Decode base64url to bytes.
fn base64url_decode(s: &str) -> Result<Vec<u8>, ()> {
    // Convert base64url to base64.
    let s = s.replace('-', "+").replace('_', "/");
    // Pad if needed.
    let padded = match s.len() % 4 {
        2 => format!("{s}=="),
        3 => format!("{s}="),
        _ => s,
    };
    // Use a simple base64 decoder.
    base64_decode(&padded)
}

/// Simple base64 decoder.
fn base64_decode(s: &str) -> Result<Vec<u8>, ()> {
    const TABLE: &[u8] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
    let mut result = Vec::new();
    let bytes = s.as_bytes();
    let mut i = 0;
    while i + 3 < bytes.len() {
        let mut vals = [0u8; 4];
        for j in 0..4 {
            if i + j >= bytes.len() || bytes[i + j] == b'=' {
                vals[j] = 255;
            } else {
                vals[j] = TABLE.iter().position(|&c| c == bytes[i + j]).unwrap_or(255) as u8;
            }
        }
        if vals[0] == 255 || vals[1] == 255 {
            break;
        }
        result.push((vals[0] << 2) | (vals[1] >> 4));
        if vals[2] != 255 {
            result.push((vals[1] << 4) | (vals[2] >> 2));
            if vals[3] != 255 {
                result.push((vals[2] << 6) | vals[3]);
            }
        }
        i += 4;
    }
    Ok(result)
}

// ── Combined filter function ─────────────────────────────────────────────

/// Apply all path-based FP filters to determine if a finding should be
/// suppressed. Returns true if the finding should be suppressed.
pub fn should_suppress_by_path(path: &Path) -> bool {
    is_vendored_path(path)
        || is_lock_file(path)
        || is_minified_path(path)
        || is_generated_path(path)
        || is_ca_certificate_path(path)
        || is_documentation_path(path)
}

/// Apply all content-based FP filters to determine if a finding should be
/// suppressed. Returns true if the finding should be suppressed.
pub fn should_suppress_by_content(matched: &str) -> bool {
    is_example_value(matched) || is_canary_token(matched) || is_hex_blob(matched) || is_uuid(matched)
}

/// Apply all path-based FP filters to a list of findings, marking
/// `likely_false_positive` for findings that match suppression criteria.
pub fn apply_path_filters(findings: &mut [Finding]) {
    for f in findings.iter_mut() {
        if should_suppress_by_path(&f.path) {
            f.likely_false_positive = true;
        }
    }
}

/// Apply all content-based FP filters to a list of findings, marking
/// `likely_false_positive` for findings that match suppression criteria.
pub fn apply_content_filters(findings: &mut [Finding]) {
    for f in findings.iter_mut() {
        if should_suppress_by_content(&f.matched) {
            f.likely_false_positive = true;
        }
    }
}

/// Apply all FP filters to a list of findings.
pub fn apply_all_filters(findings: &mut [Finding]) {
    apply_path_filters(findings);
    apply_content_filters(findings);
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::finding::Severity;
    use std::path::PathBuf;

    #[test]
    fn test_env_file_detection() {
        assert!(is_env_file(Path::new(".env")));
        assert!(is_env_file(Path::new(".env.local")));
        assert!(is_env_file(Path::new("production.env")));
        assert!(is_env_file(Path::new(".envrc")));
        assert!(!is_env_file(Path::new("main.rs")));
    }

    #[test]
    fn test_env_active_lines() {
        let content = "# comment\nKEY=value\n# another comment\nSECRET=abc123\n\n";
        let lines = parse_env_active_lines(content);
        assert_eq!(lines.len(), 2);
        assert_eq!(lines[0].0, 2);
        assert_eq!(lines[1].0, 4);
    }

    #[test]
    fn test_documentation_path() {
        assert!(is_documentation_path(Path::new("docs/guide.md")));
        assert!(is_documentation_path(Path::new("README.md")));
        assert!(is_documentation_path(Path::new("CHANGELOG.md")));
        assert!(!is_documentation_path(Path::new("src/main.rs")));
    }

    #[test]
    fn test_generated_content() {
        assert!(is_generated_content("// Code generated by protoc. DO NOT EDIT.\npackage main"));
        assert!(is_generated_content("// @generated\n\nfn main() {}"));
        assert!(!is_generated_content("fn main() { println!(\"hello\"); }"));
    }

    #[test]
    fn test_generated_path() {
        assert!(is_generated_path(Path::new("src/generated/proto.rs")));
        assert!(is_generated_path(Path::new("target/debug/main")));
        assert!(!is_generated_path(Path::new("src/main.rs")));
    }

    #[test]
    fn test_vendored_path() {
        assert!(is_vendored_path(Path::new("vendor/github.com/lib/pkg.go")));
        assert!(is_vendored_path(Path::new("node_modules/express/index.js")));
        assert!(!is_vendored_path(Path::new("src/main.rs")));
    }

    #[test]
    fn test_minified_path() {
        assert!(is_minified_path(Path::new("app.min.js")));
        assert!(is_minified_path(Path::new("style.min.css")));
        assert!(!is_minified_path(Path::new("app.js")));
    }

    #[test]
    fn test_lock_file() {
        assert!(is_lock_file(Path::new("package-lock.json")));
        assert!(is_lock_file(Path::new("Cargo.lock")));
        assert!(is_lock_file(Path::new("yarn.lock")));
        assert!(!is_lock_file(Path::new("package.json")));
    }

    #[test]
    fn test_binary_content() {
        assert!(is_binary_content(b"\x00\x01\x02\x03"));
        assert!(is_binary_content(&[0xFF, 0xFE, 0x00, 0x01]));
        assert!(!is_binary_content(b"Hello, world!\n"));
    }

    #[test]
    fn test_ca_certificate_path() {
        assert!(is_ca_certificate_path(Path::new("/etc/ssl/certs/ca-cert.pem")));
        assert!(!is_ca_certificate_path(Path::new("src/keys/server.pem")));
    }

    #[test]
    fn test_example_value() {
        assert!(is_example_value("AKIAIOSFODNN7EXAMPLE"));
        assert!(is_example_value("YOUR_API_KEY_HERE"));
        assert!(is_example_value("placeholder_secret"));
        assert!(is_example_value("CHANGEME"));
        assert!(!is_example_value("AKIAIOSFODNN7TGCA"));
    }

    #[test]
    fn test_canary_token() {
        assert!(is_canary_token("AKIAIOSFODNN7EXAMPLE"));
        assert!(is_canary_token("ghp_exampletoken123"));
        assert!(!is_canary_token("AKIAIOSFODNN7TGCA"));
    }

    #[test]
    fn test_context_aware_entropy() {
        let threshold = context_aware_entropy_threshold(Path::new("config.json"));
        assert!(threshold >= 3.0);
        let threshold_env = context_aware_entropy_threshold(Path::new(".env"));
        assert!(threshold_env <= 2.5);
    }

    #[test]
    fn test_hex_blob() {
        assert!(is_hex_blob("a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2"));
        assert!(is_hex_blob("e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"));
        assert!(!is_hex_blob("AKIAIOSFODNN7TGCA"));
    }

    #[test]
    fn test_uuid() {
        assert!(is_uuid("550e8400-e29b-41d4-a716-446655440000"));
        assert!(!is_uuid("AKIAIOSFODNN7TGCA"));
        assert!(!is_uuid("550e8400-e29b-41d4-a716"));
    }

    #[test]
    fn test_jwt_structure() {
        // Valid JWT structure (header.payload.signature).
        let jwt = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIn0.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c";
        assert!(is_valid_jwt_structure(jwt));
        assert!(!is_valid_jwt_structure("not.a.jwt"));
        assert!(!is_valid_jwt_structure("tooShort"));
    }

    #[test]
    fn test_should_suppress_by_path() {
        assert!(should_suppress_by_path(Path::new("node_modules/express/index.js")));
        assert!(should_suppress_by_path(Path::new("Cargo.lock")));
        assert!(should_suppress_by_path(Path::new("docs/guide.md")));
        assert!(!should_suppress_by_path(Path::new("src/main.rs")));
    }

    #[test]
    fn test_should_suppress_by_content() {
        assert!(should_suppress_by_content("AKIAIOSFODNN7EXAMPLE"));
        assert!(should_suppress_by_content("550e8400-e29b-41d4-a716-446655440000"));
        assert!(!should_suppress_by_content("AKIAIOSFODNN7TGCA"));
    }

    #[test]
    fn test_apply_all_filters() {
        let mut findings = vec![
            Finding {
                rule_id: "aws-access-key-id".to_string(),
                description: "AWS Access Key".to_string(),
                severity: Severity::High,
                path: PathBuf::from("src/main.rs"),
                line: 1,
                column: 1,
                matched: "AKIAIOSFODNN7EXAMPLE".to_string(),
                context: "key = AKIAIOSFODNN7EXAMPLE".to_string(),
                commit: None,
                likely_false_positive: false,
                verification: None,
            },
            Finding {
                rule_id: "aws-access-key-id".to_string(),
                description: "AWS Access Key".to_string(),
                severity: Severity::High,
                path: PathBuf::from("node_modules/lib/index.js"),
                line: 1,
                column: 1,
                matched: "AKIAIOSFODNN7TGCA".to_string(),
                context: "key = AKIAIOSFODNN7TGCA".to_string(),
                commit: None,
                likely_false_positive: false,
                verification: None,
            },
        ];
        apply_all_filters(&mut findings);
        assert!(findings[0].likely_false_positive); // Example value
        assert!(findings[1].likely_false_positive); // Vendored path
    }
}
